# Generated by Django 5.2.1 on 2025-06-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAutenticacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuário AD')),
                ('ad_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha AD')),
                ('azure_tenant_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Azure Tenant ID')),
                ('azure_client_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Azure Client ID')),
                ('azure_resource', models.CharField(blank=True, max_length=255, null=True, verbose_name='Azure Resource')),
                ('azure_audience', models.CharField(blank=True, max_length=255, null=True, verbose_name='Azure Audience')),
                ('azure_relying_party_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Azure Relying Party ID')),
                ('azure_client_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Azure Client Secret')),
            ],
            options={
                'verbose_name': 'Configuração de Autenticação',
                'verbose_name_plural': 'Configurações de Autenticação',
            },
        ),
    ]
