# Generated by Django 5.2.4 on 2025-07-17 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoautenticacao',
            name='azure_client_secret',
        ),
    ]
