# Generated by Django 5.2.4 on 2025-07-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_django', '0002_remove_configuracaoautenticacao_azure_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoautenticacao',
            name='azure_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Azure Client Secret'),
        ),
    ]
