# Generated by Django 5.2.4 on 2025-07-02 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleAprovacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovacao_automatica', models.BooleanField(default=False, verbose_name='Aprovação automática de requisições')),
            ],
            options={
                'verbose_name': 'Controle de Aprovações',
                'verbose_name_plural': 'Controle de Aprovações',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.PositiveIntegerField(blank=True, null=True)),
                ('mes_referencia', models.PositiveIntegerField(blank=True, null=True)),
                ('localizacao_tribunal', models.CharField(blank=True, max_length=100, null=True)),
                ('localizacao_secao', models.CharField(blank=True, max_length=100, null=True)),
                ('localizacao_subsecao', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_patrimonial', models.CharField(blank=True, max_length=50, null=True)),
                ('classificacao_grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('ano_fabricacao', models.PositiveIntegerField()),
                ('potencia_cv', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('complemento_ac', models.BooleanField(default=False)),
                ('complemento_dh', models.BooleanField(default=False)),
                ('complemento_ve', models.BooleanField(default=False)),
                ('complemento_te', models.BooleanField(default=False)),
                ('complemento_bag', models.BooleanField(default=False)),
                ('complemento_abs', models.BooleanField(default=False)),
                ('tipo_combustivel', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_conservacao', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_atual_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=100)),
                ('data_utilizacao', models.DateTimeField()),
                ('itinerario', models.CharField(max_length=200)),
                ('natureza_servico', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada')], default='ativa', max_length=20)),
                ('status_aprovacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=10)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('data_chegada', models.DateTimeField(blank=True, null=True)),
                ('km_saida', models.CharField(max_length=20)),
                ('km_chegada', models.CharField(blank=True, max_length=20, null=True)),
                ('ocorrencias', models.TextField(blank=True)),
                ('assinatura_motorista', models.CharField(blank=True, max_length=100)),
                ('assinatura_usuario', models.CharField(blank=True, max_length=100)),
                ('motivo_km_saida_divergente', models.TextField(blank=True)),
                ('nome_motorista', models.CharField(blank=True, max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='controlefrota.veiculo')),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisição',
            },
        ),
    ]
