# Generated by Django 5.2.1 on 2025-06-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao_tribunal', models.CharField(blank=True, max_length=100, null=True)),
                ('localizacao_secao', models.CharField(blank=True, max_length=100, null=True)),
                ('localizacao_subsecao', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_patrimonial', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('chassi', models.CharField(max_length=50, unique=True)),
                ('numero_motor', models.CharField(max_length=50, unique=True)),
                ('ano_fabricacao', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('potencia_cv', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('complemento_ac', models.BooleanField(default=False)),
                ('complemento_dh', models.BooleanField(default=False)),
                ('complemento_ve', models.BooleanField(default=False)),
                ('complemento_te', models.BooleanField(default=False)),
                ('complemento_bag', models.BooleanField(default=False)),
                ('complemento_abs', models.BooleanField(default=False)),
                ('tipo_combustivel', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_conservacao', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_atual_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacidade', models.PositiveIntegerField()),
                ('fornecedor', models.CharField(max_length=100)),
                ('documento_fornecedor', models.CharField(max_length=100)),
                ('certificado', models.CharField(blank=True, max_length=50, null=True)),
                ('seguradora', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_apolice', models.CharField(blank=True, max_length=50, null=True)),
                ('chip_identificacao', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('hodometro', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
