# Generated by Django 5.2.1 on 2025-06-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='classificacao_grupo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
