# Generated by Django 5.2.4 on 2025-07-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
