# Generated by Django 5.2.1 on 2025-06-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0002_veiculo_classificacao_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ano_referencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='mes_referencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
