# Generated by Django 5.2.4 on 2025-07-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0002_agente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeriasAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias', to='controlefrota.agente')),
            ],
        ),
    ]
