# Generated by Django 5.2.1 on 2025-06-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0003_veiculo_ano_referencia_veiculo_mes_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='capacidade',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='certificado',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='chassi',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='chip_identificacao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='documento_fornecedor',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='hodometro',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='numero_apolice',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='numero_motor',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='seguradora',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='valor_aquisicao',
        ),
    ]
