# Generated by Django 5.2.4 on 2025-07-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0004_agente_ferias_alter_feriasagente_agente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='ferias',
        ),
        migrations.AddField(
            model_name='agente',
            name='ferias_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim das Férias'),
        ),
        migrations.AddField(
            model_name='agente',
            name='ferias_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início das Férias'),
        ),
    ]
