# Generated by Django 5.2.1 on 2025-06-18 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0004_remove_veiculo_ativo_remove_veiculo_capacidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=100)),
                ('data_utilizacao', models.DateField()),
                ('horario', models.CharField(max_length=20)),
                ('itinerario', models.CharField(max_length=200)),
                ('natureza_servico', models.CharField(max_length=200)),
                ('autenticacao', models.DateField()),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada')], default='ativa', max_length=20)),
                ('aprovada', models.BooleanField(default=False)),
                ('data_saida', models.DateTimeField()),
                ('data_chegada', models.DateTimeField(blank=True, null=True)),
                ('km_saida', models.CharField(max_length=20)),
                ('km_chegada', models.CharField(blank=True, max_length=20, null=True)),
                ('ocorrencias', models.TextField(blank=True)),
                ('assinatura_motorista', models.CharField(blank=True, max_length=100)),
                ('assinatura_usuario', models.CharField(blank=True, max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='controlefrota.veiculo')),
            ],
        ),
    ]
