# Generated by Django 5.2.1 on 2025-06-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0005_requisicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicao',
            options={'verbose_name': 'Requisição', 'verbose_name_plural': 'Requisição'},
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='aprovada',
        ),
        migrations.AddField(
            model_name='requisicao',
            name='status_aprovacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=10),
        ),
    ]
