# Generated by Django 5.2.1 on 2025-06-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0006_alter_requisicao_options_remove_requisicao_aprovada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='motivo_km_saida_divergente',
            field=models.TextField(blank=True),
        ),
    ]
