# Generated by Django 5.2.1 on 2025-06-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0007_requisicao_motivo_km_saida_divergente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='autenticacao',
        ),
        migrations.AddField(
            model_name='requisicao',
            name='nome_motorista',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
