# Generated by Django 5.2.4 on 2025-07-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0007_escala_codigo_escala_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='data_inicio_escala',
            field=models.DateField(blank=True, null=True, verbose_name='Início da Escala'),
        ),
    ]
