# Generated by Django 5.2.4 on 2025-07-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0008_agente_data_inicio_escala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='nome',
        ),
    ]
