# Generated by Django 5.2.1 on 2025-06-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0008_remove_requisicao_autenticacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
