# Generated by Django 5.2.1 on 2025-06-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0009_alter_requisicao_data_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='horario',
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data_utilizacao',
            field=models.DateTimeField(),
        ),
    ]
