# Generated by Django 5.2.4 on 2025-07-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0009_remove_escala_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='ciclo',
            field=models.PositiveIntegerField(default=1, verbose_name='Ciclo (dias)'),
        ),
    ]
