# Generated by Django 5.2.4 on 2025-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0011_remove_agente_escala_plantaoagente_delete_escala'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='previsao_termino_utilizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
