# Generated by Django 5.2.4 on 2025-07-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0012_requisicao_previsao_termino_utilizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
