# Generated by Django 5.2.4 on 2025-07-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefrota', '0013_agente_ativo_veiculo_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantaoagente',
            name='status',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
